"SikuliLogo.png"
"btnnightly.png"
"netblogo.png"
"nightly.png"
"quickstart.png"
"raimanlogo.png"
"sxpower.png"
nbicons = "nbicons.png"
"firefox.png"
icon1 = "icon1.png"
icon2 = "icon2.png"
icon3 = "icon3.png"
github = "github.png"